version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll build
      - run: ./deploy.sh
